// src/videos.js
const videos = [
  { id: 1, title: "Introduction", src: "/videos/1 Introduction.mp4" },
  { id: 2, title: "The Undeniable Power of Ethical Hacking", src: "/videos/2 02 The Undeniable Power of Ethical Hacking.mp4" },
  { id: 3, title: "Why KALI", src: "/videos/3 03 Why KALI.mp4" },
  { id: 4, title: "Different Installation Methods", src: "/videos/4 04 Different Installation Methods.mp4" },
  { id: 5, title: "Install KALI (Command Center)", src: "/videos/5 05 Install KALI (Command Center).mp4" },
  { id: 6, title: "Root User Color Coding", src: "/videos/6 06 Root User Color Coding.mp4" },
  { id: 7, title: "Understand Color Codings", src: "/videos/7 07 Understand Color Codings.mp4" },
  { id: 8, title: "Update, Upgrade, and Alias", src: "/videos/8 08 Update, Upgrade, and Alias Commands.mp4" },
  { id: 9, title: "Installing Windows", src: "/videos/9 09 Installing Windows.mp4" },
  { id: 10, title: "Get Started with Linux Commands", src: "/videos/10 10 Get Started with Linux Commands.mp4" },
  { id: 11, title: "Master KALI Desktop", src: "/videos/11 11 Master KALI Desktop Environment.mp4" },
  { id: 12, title: "Steps to plan a successful attack", src: "/videos/12 12 Steps to plan a successfull pentest.mp4" },
  { id: 13, title: "Threat Modeling", src: "/videos/13 13 Threat Modeling.mp4" },
  { id: 14, title: "Wireshark Simplified", src: "/videos/14 14 Wireshark Simplified.mp4" },
  { id: 15, title: "How Does Port Scanning Work", src: "/videos/15 15 How Does Port Scanning Work.mp4" },
  { id: 16, title: "Introducing NMAP", src: "/videos/16 16 Introducing NMAP.mp4" },
  { id: 17, title: "NMAP and ZENMAP Simplified", src: "/videos/17 17 NMAP and ZENMAP Simplified.mp4" },
  { id: 18, title: "Understand NETBIOS and SMB", src: "/videos/18 18 Understand NETBIOS and SMB Attacks.mp4" },
  { id: 19, title: "Execute Man in the Middle Attack", src: "/videos/19 19 Execute Man in the Middle Attacks.mp4" },
  { id: 20, title: "Perform a DNS Spoofing Attack", src: "/videos/20 20 Perform a DNS Spoofing Attack.mp4" },
  { id: 21, title: "Identify a DNS Zone Transfer", src: "/videos/21 21 Identify a DNS Zone Transfer Vulnerability.mp4" },
  { id: 22, title: "Plan DOS and DDOS Attacks", src: "/videos/22 22 Plan DOS and DDOS Attacks.mp4" },
  { id: 23, title: "All in one Metasploit Framework", src: "/videos/23 23 All in one Metasploit Framework.mp4" },
  { id: 24, title: "Transferring The Payload", src: "/videos/24 24 Transfering The Payload to Windows Machine.mp4" },
  { id: 25, title: "Create Your First Trojan and Infiltrate", src: "/videos/25 25 Create Your First Trojan and Infiltrate a Target.mp4" },
  { id: 26, title: "The Powerful Armitage Tool", src: "/videos/26 26 The Powerful Armitage Tool.mp4" },
  { id: 27, title: "Hide a Payload in a JPEG Image", src: "/videos/27 27 Hide a Payload in a JPEG Image.mp4" },
  { id: 28, title: "How to Attack Modern Wireless", src: "/videos/28 28 How to Attack Modern Wireless Networks Introduction.mp4" },
  { id: 29, title: "Cracking WEP", src: "/videos/29 29 Cracking WEP.mp4" },
  { id: 30, title: "Cracking WPA and WPA2", src: "/videos/30 30 Cracking WPA and WPA2.mp4" },
  { id: 31, title: "WPS Cracking", src: "/videos/31 31 WPS Cracking.mp4" },
  { id: 32, title: "Tips to Improve Your Wireless", src: "/videos/32 32 Tips to Improve Your Wireless Network Security.mp4" },
  { id: 33, title: "Web Applications Security Overview", src: "/videos/33 33 Web Applications Security Overview.mp4" },
  { id: 34, title: "Web Applications Attack Surface", src: "/videos/34 34 Web Applications Attack Surface.mp4" },
  { id: 35, title: "Metasploitable VM", src: "/videos/35 35 Metasploitable VM.mp4" },
  { id: 36, title: "Discover Vulnerabilities in Websites", src: "/videos/36 36 Discover Vulnerabilities in Websites.mp4" },
  { id: 37, title: "Control a Database Server", src: "/videos/37 37 Control a Database Server with SQLMap.mp4" },
  { id: 38, title: "Easily Hack a WordPress Site", src: "/videos/38 38 Easily Hack a WordPress Site.mp4" },
  { id: 39, title: "Intercept Analyze and Replay Web Traffic", src: "/videos/39 39 Intercept Analyze and Replay Web Traffic.mp4" },
  { id: 40, title: "Various Password Attacks", src: "/videos/40 40 Various Password Attacks.mp4" },
  { id: 41, title: "Hashing in a Nutshell", src: "/videos/41 41 Hashing in a Nutshell.mp4" },
  { id: 42, title: "Execute an Offline Password Attack", src: "/videos/42 42 Execute an Offline Password Attack on Windows.mp4" },
  { id: 43, title: "Collect and Visualize Data with Wireshark", src: "/videos/43 43 Collect and Visualize Data with Maltego.mp4" },
  { id: 44, title: "Execute an Offline Password Attack Continued", src: "/videos/44 44 Execute an Offline Password Attack in Linux.mp4" },
  { id: 45, title: "Run an Online Password Attack on a Website", src: "/videos/45 45 Run an Online Password Attack on a Router.mp4" },
  { id: 46, title: "Run an Online Password Attack on Email", src: "/videos/46 46 Run an Online Password Attack on Linux.mp4" },
  { id: 47, title: "Crack Passwords with Rainbow Tables", src: "/videos/47 47 Crack Passwords with Rainbow Tables.mp4" },
  { id: 48, title: "Design Effective Wordlists", src: "/videos/48 48 Design Effective Wordlists.mp4" },
  { id: 49, title: "Password Management Tips", src: "/videos/49 49 Password Management Tips.mp4" },
  { id: 50, title: "SE Attack", src: "/videos/50 50 SE Attack Vectors new.mp4" },
  { id: 51, title: "Open source Intelligence", src: "/videos/51 51 Open source Intelligence (OSINT).mp4" },
  { id: 52, title: "Google Dorks Live Examples", src: "/videos/52 52 Google Dorks Live Examples.mp4" },
  { id: 53, title: "Execute a Phishing Attack", src: "/videos/53 53 Execute a Phishing Attack.mp4" },
  { id: 54, title: "Hack Facebook, Twitter, and Gmail Accounts", src: "/videos/54 54 Hack Facebook, Twitter, and Gmail Accounts.mp4" },
  { id: 55, title: "Mobile Attacks Surface", src: "/videos/55 55 Mobile Attacks Surface.mp4" },
  { id: 56, title: "Decrypt SSL Session", src: "/videos/56 56 Decrypt SSL Session.mp4" },
  { id: 57, title: "Reverse Engineer an Android App", src: "/videos/57 57 Reverse Engineer an Android Application.mp4" },
  { id: 58, title: "Hack an Android Phone with Armitage", src: "/videos/58 58 Hack an Android Phone with Armitage.mp4" },
  { id: 59, title: "Post Exploitation in Terminal", src: "/videos/59 59 Post Exploitation Terminologies.mp4" },
  { id: 60, title: "Backdoor Tools Explained", src: "/videos/60 60 Backdoor Tools Explained.mp4" },
  { id: 61, title: "Netcat Simplified", src: "/videos/61 61 Netcat Simplified.mp4" },
  { id: 62, title: "Install a Backdoor", src: "/videos/62 62 Install a Backdoor.mp4" },
  { id: 63, title: "Deface a Website in Few Seconds", src: "/videos/63 63 Deface a Website in Few Seconds.mp4" },
  { id: 64, title: "Create a Simple Ransomware", src: "/videos/64 64 Create a Simple Ransomware.mp4" },
  { id: 65, title: "Hidden Tear Ransomware", src: "/videos/65 65 Hidden Tear Ransomware Setup.mp4" },
  { id: 66, title: "Bypass Firewalls by Tunneling", src: "/videos/66 66 Bypass Firewalls by Tunneling Data and Commands over DNS new.mp4" },
  { id: 67, title: "Publish Your Weaponized Code", src: "/videos/67 67 Publish Your Weapons Online.mp4" },
  { id: 68, title: "Stay Anonymous Online", src: "/videos/68 68 Stay Anonymous Online.mp4" },
  { id: 69, title: "Stealthy Command and Control", src: "/videos/69 69 Setup a Stealthy Command and Control Center Online.mp4" },
  { id: 70, title: "Broken Access Control / Router Access Control", src: "/videos/70 70 Broken Access Control.mp4" },

  // 71-83 from your latest screenshot:
  { id: 71, title: "Broken Authentication", src: "/videos/71 71 Broken Authentication.mp4" },
  { id: 72, title: "Components with Known Vulnerabilities", src: "/videos/72 72 Components with Known Vulnerabilities.mp4" },
  { id: 73, title: "Cross Site Scripting (XSS)", src: "/videos/73 73 Cross Site Scripting.mp4" },
  { id: 74, title: "Injection", src: "/videos/74 74 Injection.mp4" },
  { id: 75, title: "Insecure Deserialization", src: "/videos/75 75 Insecure Deserialization.mp4" },
  { id: 76, title: "Insufficient Logging and Monitoring", src: "/videos/76 76 Insufficient Logging and Monitoring.mp4" },
  { id: 77, title: "Security Misconfiguration", src: "/videos/77 77 Security Misconfiguration.mp4" },
  { id: 78, title: "Sensitive Data Exposure", src: "/videos/78 78 Sensitive Data Exposure.mp4" },
  { id: 79, title: "XML External Entity (XXE)", src: "/videos/79 79 XML External Entity.mp4" },
  { id: 80, title: "How to Prepare and Present Your Findings", src: "/videos/80 80 How to Prepare and Present Your Report final mp4 new.mp4" },
  { id: 81, title: "How Can Pentest...", src: "/videos/81 81 How Can Pentest.mp4" },
  { id: 82, title: "Create an IoT WIFI Jammer", src: "/videos/82 82 Create an IoT WIFI Jammer.mp4" },
  { id: 83, title: "Create a $3 Rubber Ducky Key", src: "/videos/83 83 Create a $3 Rubber Ducky Key logger new.mp4" }
];

export default videos;
